# Generated by Django 2.2.4 on 2019-08-22 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_auto_20190822_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='highlighted',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='owner',
        ),
    ]
